In [1]:
from transformers import pipeline

C:\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

All model checkpoint layers were used when initializing TFBartForConditionalGeneration.

All the layers of TFBartForConditionalGeneration were initialized from the model checkpoint at facebook/bart-large-cnn.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBartForConditionalGeneration for predictions without further training.


In [3]:
ARTICLE = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."

In [4]:
print(summarizer(ARTICLE, max_length=60, min_length=30, do_sample=False))

[{'summary_text': "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. It was popularised in the 1960s with the release of Letraset sheets."}]


In [5]:
from transformers import RobertaTokenizer, TFRobertaModel

In [6]:
tokenizer = RobertaTokenizer.from_pretrained('roberta-large')
model = TFRobertaModel.from_pretrained('roberta-large')

Some layers from the model checkpoint at roberta-large were not used when initializing TFRobertaModel: ['lm_head']
- This IS expected if you are initializing TFRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFRobertaModel were initialized from the model checkpoint at roberta-large.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaModel for predictions without further training.


In [7]:
model.summary()

Model: "tf_roberta_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 roberta (TFRobertaMainLayer  multiple                 355359744 
 )                                                               
                                                                 
Total params: 355,359,744
Trainable params: 355,359,744
Non-trainable params: 0
_________________________________________________________________


In [8]:
text = "Lorem Ipsum is simply dummy text of the printing and typesetting industry"
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)

In [9]:
print(output)

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 17, 1024), dtype=float32, numpy=
array([[[-0.06556174, -0.08852815, -0.02000626, ..., -0.11277131,
          0.18897784,  0.12333396],
        [ 0.02408867,  0.08807859, -0.2706828 , ...,  0.06151231,
         -0.20081146, -0.03543307],
        [ 0.08181281,  0.07480118, -0.24081755, ..., -0.1555765 ,
          0.530776  ,  0.06391553],
        ...,
        [-0.05194158,  0.26970786, -0.525902  , ..., -0.01453426,
          0.2245437 ,  0.20920593],
        [-0.02740651,  0.20386069, -0.36803162, ..., -0.21442485,
          0.03581668,  0.2231814 ],
        [-0.02596354, -0.07665968,  0.02093653, ..., -0.1460183 ,
          0.13287024,  0.04350654]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 1024), dtype=float32, numpy=
array([[ 0.16108422,  0.6981167 ,  0.45465714, ...,  0.05722639,
         0.33975062, -0.37429762]], dtype=float32)>, past_key_values=None, hidden_states=None, attentions=